version: "3.8"
services:
  main-reverse-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: main-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - application
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

  ssl-provider:
    image: jrcs/letsencrypt-nginx-proxy-companion
    networks:
      - application
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=
      - NGINX_PROXY_CONTAINER=main-reverse-proxy

  reverse-proxy:
    image: shaoyi1997/idealize-reverse-proxy:latest
    container_name: reverse-proxy
    restart: always
    networks:
      - application
      - frontend
      - backend
    ports:
      - "80:80"
    depends_on:
      - app
      - api
    links:
      - app:app
      - api:api
    environment:
      - VIRTUAL_HOST=
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=

  app:
    image: shaoyi1997/idealize-app:latest
    container_name: app
    restart: always
    depends_on:
      - api
    links:
      - api:api
    networks:
      - frontend
    ports:
      - "3000:3000"
    command: ["nginx", "-g", "daemon off;"]

  api:
    image: shaoyi1997/idealize-api
    container_name: api
    restart: always
    depends_on:
      - postgres
    links:
      - postgres:postgres
    environment:
      DATABASE_URL: postgres://idealize:idealize@postgres:5432/idealize
      NODE_ENV: production
      PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - backend
    volumes:
      - api_node_modules:/app/node_modules
    command: ["yarn", "start"]

  postgres:
    image: postgres:11.9
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      POSTGRES_USER: idealize
      POSTGRES_PASSWORD: idealize
      POSTGRES_DB: idealize
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  frontend:
  backend:
  application:

volumes:
  pgdata:
  api_node_modules:
  app_node_modules:
  nginx-certs:
  nginx-vhost:
  nginx-html:
